version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "22:00"
    timezone: "UTC"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
    day: "sunday"
    time: "22:00"
    timezone: "UTC"
  ignore:
    - dependency-name: "*"
      # don't suggest major version upgrades by default
      update-types: ["version-update:semver-major"]
