name: CI
on:
  push:
    branches: [ master, "feature/*", "bugfix/*", "release/*", "maintenance/*" ]
  pull_request:
    branches: [ master ]

# TODO: work out how many of these tests configs still make sense now that we use 
# pyca/cryptography for all crypto operations (and oscrypto just serves as a means
# to access the system trust)
jobs:
  build:
    name: Python ${{ matrix.python }} on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          #- macOS-latest # excluded for now due to libcrypto issues in the image
          - windows-2019
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
        arch:
          - 'x86'
          - 'x64'
        exclude:
          - os: ubuntu-18.04
            arch: x86
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pytest
      - name: Run test suite
        run: python -m pytest
